# Counting DNA Nucleotides

# Sample Dataset
# AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

# Sample Output
# 20 12 17 21

#test_data = "TCCCTCTTCGGATGTAGTTAAGCATCTTACATCGGGCAAATACATACCCATAAACGTTACCTCAGGGACGATGTCAAAAGTAAGCATGCGCATCTATTTAACCTTCCAAATTACCGTGATGTGAACGCCCTGAAACATTAACTCGAGATATAGCCATGCTCTATCAAGAATAAGTAAGTGATGCGTCCTTCTCGGTCTACGCACTCTGGAACTAAGAGGCCTGCTTAAAGCCACGGTAATTCCGTTTTACTAATCTAGCGAACGGATATTATTCCATGCGGAGGCGAGGAGCAGTTCGCCACCGGGAGAAGCGCAGTTAACAATTCATGGGTGTTGCTGTCTGACCGGGGGTAGCTCTCCGTTACCACGTAGTTTTAGATCTCCAATCGAGAAGACGCACACGGCCATGTACTTTTGCGATACAAAAAGTGGTTCAAGAGGCAAGGCGCGATTGAATACCAAAATAGGACAAGTTCGAGTCCCACCCGACAGTAGTTACCCGCTTCGGGTTTGACTCCCGCATTTCCATGTCGCTGCATAGCGTGACTAACTGTTACTCGAGAGCTCGTTGAAGGTGGTTTACGATCTGCCCGATTTTTCTAAGACAGCTACTCACCTAATTATCCCAGTGGAGCGCGGGTCTAGTATTAGACCAGTGCATACCTGTTGCCAAACACGGTATTAGGATGTAGTCAACCTCAGGTTAGGTGATACACCTTCACGTCTGCCTGGGTGCATGGCCAGCGTCAGCGAGTTCAGTCGTTCATAGGTTGGATTCAATGCCTAGGCGAAGTGTTTGCCCGCGGCGAGGGACACGCCTGGATACTTATACTAATCGGGCAACACGCGCCGACCTGGTCAGCCTTTAGTCGACTTTAGTCGATCAACGGTGTACATATATAGGCGCACTAGAATCATGACGAGGGGTCGCTCTCTCTACGAGTGTTCTAAATGCTGGTGCCTATTGTGGCTTTACGAAGGCGTG"

def count_nucleotides_long(data):
  a = 0
  c = 0
  g = 0
  t = 0

  for nucleotide in data:
    if nucleotide.upper() == 'A':
      a += 1
    elif nucleotide.upper() == 'C':
      c += 1
    elif nucleotide.upper() == 'G':
      g += 1
    elif nucleotide.upper() == 'T':
      t += 1

  return str(a) + ' ' + str(c) + ' ' + str(g) + ' ' + str(t)


def count_nucleotides_short(data):
  counts = (data.count(nucleotide) for nucleotide in "ACGT")
  return ' '.join(map(str, counts))
